package configs;

import com.google.common.collect.Iterators;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import vcsFeaturesMM.LowLevelCommand;

@SuppressWarnings("all")
public class PluginGenerator implements ConfigGenerator {
  @Override
  public CharSequence generate(final Resource resource) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<?eclipse version=\"3.4\"?>");
    _builder.newLine();
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("id=\"product\"");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.core.runtime.products\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<product");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("application=\"org.eclipse.e4.ui.workbench.swt.E4Application\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"vcsfeatures\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<property");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("name=\"applicationCSS\"");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("value=\"platform:/plugin/VCSFeatures/css/default.css\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</property>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</product>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.ui.commands\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<category");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.commands.category\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Sample Category\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</category>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<category");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"UI Commands\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</category>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.commands.category\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("description=\"This command is used to rename JGit commands (give aliases)\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.commands.renameCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Rename Command\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    {
      Iterable<LowLevelCommand> _iterable = IteratorExtensions.<LowLevelCommand>toIterable(Iterators.<LowLevelCommand>filter(resource.getAllContents(), LowLevelCommand.class));
      for(final LowLevelCommand llc : _iterable) {
        _builder.append("      ");
        _builder.append("<command");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("      ");
        _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("      ");
        _builder.append("id=\"VCSFeatures.");
        String _name = llc.getCommand().getName();
        _builder.append(_name, "            ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("      ");
        _builder.append("name=\"");
        String _name_1 = llc.getName();
        _builder.append(_name_1, "            ");
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("</command>");
        _builder.newLine();
      }
    }
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.ui.handlers\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.RenameHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.commands.renameCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    {
      Iterable<LowLevelCommand> _iterable_1 = IteratorExtensions.<LowLevelCommand>toIterable(Iterators.<LowLevelCommand>filter(resource.getAllContents(), LowLevelCommand.class));
      for(final LowLevelCommand llc_1 : _iterable_1) {
        _builder.append("<handler\t\t\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("class=\"handlers.");
        String _get = llc_1.getCommand().getName().split("Command")[0];
        String _plus = (_get + "Handler");
        _builder.append(_plus, "\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("commandId=\"VCSFeatures.");
        String _name_2 = llc_1.getCommand().getName();
        _builder.append(_name_2, "\t");
        _builder.append("\">");
        _builder.newLineIfNotEmpty();
        _builder.append("</handler>");
        _builder.newLine();
      }
    }
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("point=\"org.eclipse.ui.menus\">");
    _builder.newLine();
    _builder.append("   \t\t");
    _builder.append("<menuContribution");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("allPopups=\"false\"");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("locationURI=\"popup:org.eclipse.ui.popup.any?after=additions\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<menu");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("id=\"org.eclipse.ui.navigator.ProjectExplorer.VCSBuilder\"");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("label=\"VCSBuilder\">");
    _builder.newLine();
    {
      Iterable<LowLevelCommand> _iterable_2 = IteratorExtensions.<LowLevelCommand>toIterable(Iterators.<LowLevelCommand>filter(resource.getAllContents(), LowLevelCommand.class));
      for(final LowLevelCommand llc_2 : _iterable_2) {
        _builder.append("<command");
        _builder.newLine();
        _builder.append("      ");
        _builder.append("commandId=\"VCSFeatures.");
        String _name_3 = llc_2.getCommand().getName();
        _builder.append(_name_3, "      ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("label=\"");
        String _name_4 = llc_2.getName();
        _builder.append(_name_4, "      ");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("      ");
        _builder.append("style=\"push\">");
        _builder.newLine();
        _builder.append("</command>");
        _builder.newLine();
      }
    }
    _builder.append("            ");
    _builder.append("</menu>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</menuContribution>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
