package configs;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Plugin implements ConfigGenerator {
  @Override
  public CharSequence generate() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<?eclipse version=\"3.4\"?>");
    _builder.newLine();
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("id=\"product\"");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.core.runtime.products\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<product");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("application=\"org.eclipse.e4.ui.workbench.swt.E4Application\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"vcsfeatures\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<property");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("name=\"applicationCSS\"");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("value=\"platform:/plugin/VCSFeatures/css/default.css\">");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</property>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</product>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.ui.commands\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<category");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.commands.category\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Sample Category\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</category>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<category");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"UI Commands\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</category>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.commands.category\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("description=\"This command is used to rename JGit commands (give aliases)\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.commands.renameCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Rename Command\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.AddCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Add\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.CheckoutCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Checkout\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.CheckoutCreateCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Checkout Create\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.CloneCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Clone\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.CommitCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Commit\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.CreateBranchCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Create Branch\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.FetchCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Fetch\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.InitCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Init\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.LogCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Log\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.OpenCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Open\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.PullCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Pull\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.PushCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Push\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.RemoteAddCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"RemoteAddCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("categoryId=\"VCSFeatures.uiCommands\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("id=\"VCSFeatures.RmCommand\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("name=\"Remove\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("point=\"org.eclipse.ui.handlers\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.RenameHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.commands.renameCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.AddHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.AddCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.CheckoutHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.CheckoutCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.CheckoutCreateHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.CheckoutCreateCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.CloneHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.CloneCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.CommitHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.CommitCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.CreateBranchHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.CreateBranchCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.FetchHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.FetchCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.InitHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.InitCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.LogHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.LogCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.OpenHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.OpenCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.PullHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.PullCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.PushHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.PushCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.RemoteAddHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.RemoteAddCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<handler");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("class=\"handlers.RmHandler\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("commandId=\"VCSFeatures.RmCommand\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</handler>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("<extension");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("point=\"org.eclipse.ui.menus\">");
    _builder.newLine();
    _builder.append("   \t\t");
    _builder.append("<menuContribution");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("allPopups=\"false\"");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("locationURI=\"popup:org.eclipse.ui.popup.any?after=additions\">");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<menu");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("id=\"org.eclipse.ui.navigator.ProjectExplorer.VCSBuilder\"");
    _builder.newLine();
    _builder.append("                  ");
    _builder.append("label=\"VCSBuilder\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.AddCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Add File\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.CheckoutCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Checkout\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.CheckoutCreateCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Checkout Create\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.CloneCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Clone\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.CommitCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Commit\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.CreateBranchCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Create Branch\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.FetchCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Fetch\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.InitCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Inititialize repository\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.LogCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Log\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.OpenCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Open repository\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.PullCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Pull\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.PushCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Push\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.RemoteAddCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Remote Add\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("<command");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("commandId=\"VCSFeatures.RmCommand\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("label=\"Remove File\"");
    _builder.newLine();
    _builder.append("                     ");
    _builder.append("style=\"push\">");
    _builder.newLine();
    _builder.append("               ");
    _builder.append("</command>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("</menu>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("</menuContribution>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</extension>");
    _builder.newLine();
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
