/*
 * generated by Xtext 2.32.0
 */
package diro.geodes.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class VcsFeaturesGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class VCSFeaturesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.VCSFeatures");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVCSFeaturesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVCSFeaturesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommandsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCommandsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCommandsCommandsParserRuleCall_4_2_0 = (RuleCall)cCommandsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCommandsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cCommandsCommandsParserRuleCall_4_3_1_0 = (RuleCall)cCommandsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHistoryKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cHistoryAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cHistoryHistoryParserRuleCall_5_2_0 = (RuleCall)cHistoryAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cHistoryAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cHistoryHistoryParserRuleCall_5_3_1_0 = (RuleCall)cHistoryAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cVersionunitKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cVersionunitAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cVersionunitVersionUnitParserRuleCall_6_2_0 = (RuleCall)cVersionunitAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cVersionunitAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cVersionunitVersionUnitParserRuleCall_6_3_1_0 = (RuleCall)cVersionunitAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCollaborationstyleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cCollaborationstyleAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cCollaborationstyleCollaborationStyleParserRuleCall_7_2_0 = (RuleCall)cCollaborationstyleAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cCollaborationstyleAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cCollaborationstyleCollaborationStyleParserRuleCall_7_3_1_0 = (RuleCall)cCollaborationstyleAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDatabaseKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cDatabaseAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cDatabaseDatabaseParserRuleCall_8_2_0 = (RuleCall)cDatabaseAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cDatabaseAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cDatabaseDatabaseParserRuleCall_8_3_1_0 = (RuleCall)cDatabaseAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//VCSFeatures returns VCSFeatures:
		//    {VCSFeatures}
		//    'VCSFeatures'
		//    name=EString
		//    '{'
		//        ('commands' '{' commands+=Commands ( "," commands+=Commands)* '}' )?
		//        ('history' '{' history+=History ( "," history+=History)* '}' )?
		//        ('versionunit' '{' versionunit+=VersionUnit ( "," versionunit+=VersionUnit)* '}' )?
		//        ('collaborationstyle' '{' collaborationstyle+=CollaborationStyle ( "," collaborationstyle+=CollaborationStyle)* '}' )?
		//        ('database' '{' database+=Database ( "," database+=Database)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VCSFeatures}
		//'VCSFeatures'
		//name=EString
		//'{'
		//    ('commands' '{' commands+=Commands ( "," commands+=Commands)* '}' )?
		//    ('history' '{' history+=History ( "," history+=History)* '}' )?
		//    ('versionunit' '{' versionunit+=VersionUnit ( "," versionunit+=VersionUnit)* '}' )?
		//    ('collaborationstyle' '{' collaborationstyle+=CollaborationStyle ( "," collaborationstyle+=CollaborationStyle)* '}' )?
		//    ('database' '{' database+=Database ( "," database+=Database)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VCSFeatures}
		public Action getVCSFeaturesAction_0() { return cVCSFeaturesAction_0; }
		
		//'VCSFeatures'
		public Keyword getVCSFeaturesKeyword_1() { return cVCSFeaturesKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('commands' '{' commands+=Commands ( "," commands+=Commands)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'commands'
		public Keyword getCommandsKeyword_4_0() { return cCommandsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//commands+=Commands
		public Assignment getCommandsAssignment_4_2() { return cCommandsAssignment_4_2; }
		
		//Commands
		public RuleCall getCommandsCommandsParserRuleCall_4_2_0() { return cCommandsCommandsParserRuleCall_4_2_0; }
		
		//( "," commands+=Commands)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//commands+=Commands
		public Assignment getCommandsAssignment_4_3_1() { return cCommandsAssignment_4_3_1; }
		
		//Commands
		public RuleCall getCommandsCommandsParserRuleCall_4_3_1_0() { return cCommandsCommandsParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('history' '{' history+=History ( "," history+=History)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'history'
		public Keyword getHistoryKeyword_5_0() { return cHistoryKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//history+=History
		public Assignment getHistoryAssignment_5_2() { return cHistoryAssignment_5_2; }
		
		//History
		public RuleCall getHistoryHistoryParserRuleCall_5_2_0() { return cHistoryHistoryParserRuleCall_5_2_0; }
		
		//( "," history+=History)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//history+=History
		public Assignment getHistoryAssignment_5_3_1() { return cHistoryAssignment_5_3_1; }
		
		//History
		public RuleCall getHistoryHistoryParserRuleCall_5_3_1_0() { return cHistoryHistoryParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('versionunit' '{' versionunit+=VersionUnit ( "," versionunit+=VersionUnit)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'versionunit'
		public Keyword getVersionunitKeyword_6_0() { return cVersionunitKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//versionunit+=VersionUnit
		public Assignment getVersionunitAssignment_6_2() { return cVersionunitAssignment_6_2; }
		
		//VersionUnit
		public RuleCall getVersionunitVersionUnitParserRuleCall_6_2_0() { return cVersionunitVersionUnitParserRuleCall_6_2_0; }
		
		//( "," versionunit+=VersionUnit)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//versionunit+=VersionUnit
		public Assignment getVersionunitAssignment_6_3_1() { return cVersionunitAssignment_6_3_1; }
		
		//VersionUnit
		public RuleCall getVersionunitVersionUnitParserRuleCall_6_3_1_0() { return cVersionunitVersionUnitParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('collaborationstyle' '{' collaborationstyle+=CollaborationStyle ( "," collaborationstyle+=CollaborationStyle)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'collaborationstyle'
		public Keyword getCollaborationstyleKeyword_7_0() { return cCollaborationstyleKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//collaborationstyle+=CollaborationStyle
		public Assignment getCollaborationstyleAssignment_7_2() { return cCollaborationstyleAssignment_7_2; }
		
		//CollaborationStyle
		public RuleCall getCollaborationstyleCollaborationStyleParserRuleCall_7_2_0() { return cCollaborationstyleCollaborationStyleParserRuleCall_7_2_0; }
		
		//( "," collaborationstyle+=CollaborationStyle)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//collaborationstyle+=CollaborationStyle
		public Assignment getCollaborationstyleAssignment_7_3_1() { return cCollaborationstyleAssignment_7_3_1; }
		
		//CollaborationStyle
		public RuleCall getCollaborationstyleCollaborationStyleParserRuleCall_7_3_1_0() { return cCollaborationstyleCollaborationStyleParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('database' '{' database+=Database ( "," database+=Database)* '}' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'database'
		public Keyword getDatabaseKeyword_8_0() { return cDatabaseKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//database+=Database
		public Assignment getDatabaseAssignment_8_2() { return cDatabaseAssignment_8_2; }
		
		//Database
		public RuleCall getDatabaseDatabaseParserRuleCall_8_2_0() { return cDatabaseDatabaseParserRuleCall_8_2_0; }
		
		//( "," database+=Database)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//database+=Database
		public Assignment getDatabaseAssignment_8_3_1() { return cDatabaseAssignment_8_3_1; }
		
		//Database
		public RuleCall getDatabaseDatabaseParserRuleCall_8_3_1_0() { return cDatabaseDatabaseParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class CommandsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.Commands");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCommandsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCommandsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cMergeStrategyKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMergeStrategyAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMergeStrategyMergeStrategyEnumRuleCall_3_1_0 = (RuleCall)cMergeStrategyAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cHighlevelcommandKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cHighlevelcommandAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cHighlevelcommandHighLevelCommandParserRuleCall_4_2_0 = (RuleCall)cHighlevelcommandAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cHighlevelcommandAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cHighlevelcommandHighLevelCommandParserRuleCall_4_3_1_0 = (RuleCall)cHighlevelcommandAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLowlevelcommandKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLowlevelcommandAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLowlevelcommandLowLevelCommandParserRuleCall_5_2_0 = (RuleCall)cLowlevelcommandAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLowlevelcommandAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cLowlevelcommandLowLevelCommandParserRuleCall_5_3_1_0 = (RuleCall)cLowlevelcommandAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Commands returns Commands:
		//    {Commands}
		//    'Commands'
		//    '{'
		//        ('mergeStrategy' mergeStrategy=MergeStrategy)?
		//        ('highlevelcommand' '{' highlevelcommand+=HighLevelCommand ( "," highlevelcommand+=HighLevelCommand)* '}' )?
		//        ('lowlevelcommand' '{' lowlevelcommand+=LowLevelCommand ( "," lowlevelcommand+=LowLevelCommand)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Commands}
		//'Commands'
		//'{'
		//    ('mergeStrategy' mergeStrategy=MergeStrategy)?
		//    ('highlevelcommand' '{' highlevelcommand+=HighLevelCommand ( "," highlevelcommand+=HighLevelCommand)* '}' )?
		//    ('lowlevelcommand' '{' lowlevelcommand+=LowLevelCommand ( "," lowlevelcommand+=LowLevelCommand)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Commands}
		public Action getCommandsAction_0() { return cCommandsAction_0; }
		
		//'Commands'
		public Keyword getCommandsKeyword_1() { return cCommandsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('mergeStrategy' mergeStrategy=MergeStrategy)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'mergeStrategy'
		public Keyword getMergeStrategyKeyword_3_0() { return cMergeStrategyKeyword_3_0; }
		
		//mergeStrategy=MergeStrategy
		public Assignment getMergeStrategyAssignment_3_1() { return cMergeStrategyAssignment_3_1; }
		
		//MergeStrategy
		public RuleCall getMergeStrategyMergeStrategyEnumRuleCall_3_1_0() { return cMergeStrategyMergeStrategyEnumRuleCall_3_1_0; }
		
		//('highlevelcommand' '{' highlevelcommand+=HighLevelCommand ( "," highlevelcommand+=HighLevelCommand)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'highlevelcommand'
		public Keyword getHighlevelcommandKeyword_4_0() { return cHighlevelcommandKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//highlevelcommand+=HighLevelCommand
		public Assignment getHighlevelcommandAssignment_4_2() { return cHighlevelcommandAssignment_4_2; }
		
		//HighLevelCommand
		public RuleCall getHighlevelcommandHighLevelCommandParserRuleCall_4_2_0() { return cHighlevelcommandHighLevelCommandParserRuleCall_4_2_0; }
		
		//( "," highlevelcommand+=HighLevelCommand)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//highlevelcommand+=HighLevelCommand
		public Assignment getHighlevelcommandAssignment_4_3_1() { return cHighlevelcommandAssignment_4_3_1; }
		
		//HighLevelCommand
		public RuleCall getHighlevelcommandHighLevelCommandParserRuleCall_4_3_1_0() { return cHighlevelcommandHighLevelCommandParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('lowlevelcommand' '{' lowlevelcommand+=LowLevelCommand ( "," lowlevelcommand+=LowLevelCommand)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lowlevelcommand'
		public Keyword getLowlevelcommandKeyword_5_0() { return cLowlevelcommandKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//lowlevelcommand+=LowLevelCommand
		public Assignment getLowlevelcommandAssignment_5_2() { return cLowlevelcommandAssignment_5_2; }
		
		//LowLevelCommand
		public RuleCall getLowlevelcommandLowLevelCommandParserRuleCall_5_2_0() { return cLowlevelcommandLowLevelCommandParserRuleCall_5_2_0; }
		
		//( "," lowlevelcommand+=LowLevelCommand)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//lowlevelcommand+=LowLevelCommand
		public Assignment getLowlevelcommandAssignment_5_3_1() { return cLowlevelcommandAssignment_5_3_1; }
		
		//LowLevelCommand
		public RuleCall getLowlevelcommandLowLevelCommandParserRuleCall_5_3_1_0() { return cLowlevelcommandLowLevelCommandParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class HistoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.History");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHistoryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHistoryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLabelTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cLabelTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cLabelTypeLabelTypeEnumRuleCall_3_1_0 = (RuleCall)cLabelTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommitHistoryRangeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCommitHistoryRangeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCommitHistoryRangeEIntParserRuleCall_4_1_0 = (RuleCall)cCommitHistoryRangeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNumberOfBranchesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNumberOfBranchesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cNumberOfBranchesEIntParserRuleCall_5_1_0 = (RuleCall)cNumberOfBranchesAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//History returns History:
		//    {History}
		//    'History'
		//    '{'
		//        ('labelType' labelType=LabelType)?
		//        ('commitHistoryRange' commitHistoryRange=EInt)?
		//        ('numberOfBranches' numberOfBranches=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{History}
		//'History'
		//'{'
		//    ('labelType' labelType=LabelType)?
		//    ('commitHistoryRange' commitHistoryRange=EInt)?
		//    ('numberOfBranches' numberOfBranches=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{History}
		public Action getHistoryAction_0() { return cHistoryAction_0; }
		
		//'History'
		public Keyword getHistoryKeyword_1() { return cHistoryKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('labelType' labelType=LabelType)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'labelType'
		public Keyword getLabelTypeKeyword_3_0() { return cLabelTypeKeyword_3_0; }
		
		//labelType=LabelType
		public Assignment getLabelTypeAssignment_3_1() { return cLabelTypeAssignment_3_1; }
		
		//LabelType
		public RuleCall getLabelTypeLabelTypeEnumRuleCall_3_1_0() { return cLabelTypeLabelTypeEnumRuleCall_3_1_0; }
		
		//('commitHistoryRange' commitHistoryRange=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'commitHistoryRange'
		public Keyword getCommitHistoryRangeKeyword_4_0() { return cCommitHistoryRangeKeyword_4_0; }
		
		//commitHistoryRange=EInt
		public Assignment getCommitHistoryRangeAssignment_4_1() { return cCommitHistoryRangeAssignment_4_1; }
		
		//EInt
		public RuleCall getCommitHistoryRangeEIntParserRuleCall_4_1_0() { return cCommitHistoryRangeEIntParserRuleCall_4_1_0; }
		
		//('numberOfBranches' numberOfBranches=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'numberOfBranches'
		public Keyword getNumberOfBranchesKeyword_5_0() { return cNumberOfBranchesKeyword_5_0; }
		
		//numberOfBranches=EInt
		public Assignment getNumberOfBranchesAssignment_5_1() { return cNumberOfBranchesAssignment_5_1; }
		
		//EInt
		public RuleCall getNumberOfBranchesEIntParserRuleCall_5_1_0() { return cNumberOfBranchesEIntParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class VersionUnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.VersionUnit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVersionUnitAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVersionUnitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cGranularityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cGranularityAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cGranularityVersionUnitTypeEnumRuleCall_3_2_0 = (RuleCall)cGranularityAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cGranularityAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cGranularityVersionUnitTypeEnumRuleCall_3_3_1_0 = (RuleCall)cGranularityAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//VersionUnit returns VersionUnit:
		//    {VersionUnit}
		//    'VersionUnit'
		//    '{'
		//        ('granularity' '{' granularity+=VersionUnitType ( "," granularity+=VersionUnitType)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VersionUnit}
		//'VersionUnit'
		//'{'
		//    ('granularity' '{' granularity+=VersionUnitType ( "," granularity+=VersionUnitType)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VersionUnit}
		public Action getVersionUnitAction_0() { return cVersionUnitAction_0; }
		
		//'VersionUnit'
		public Keyword getVersionUnitKeyword_1() { return cVersionUnitKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('granularity' '{' granularity+=VersionUnitType ( "," granularity+=VersionUnitType)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'granularity'
		public Keyword getGranularityKeyword_3_0() { return cGranularityKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//granularity+=VersionUnitType
		public Assignment getGranularityAssignment_3_2() { return cGranularityAssignment_3_2; }
		
		//VersionUnitType
		public RuleCall getGranularityVersionUnitTypeEnumRuleCall_3_2_0() { return cGranularityVersionUnitTypeEnumRuleCall_3_2_0; }
		
		//( "," granularity+=VersionUnitType)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//granularity+=VersionUnitType
		public Assignment getGranularityAssignment_3_3_1() { return cGranularityAssignment_3_3_1; }
		
		//VersionUnitType
		public RuleCall getGranularityVersionUnitTypeEnumRuleCall_3_3_1_0() { return cGranularityVersionUnitTypeEnumRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class CollaborationStyleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.CollaborationStyle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCollaborationStyleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCollaborationStyleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCollabStyleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCollabStyleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCollabStyleCollaborationStyleTypeEnumRuleCall_3_1_0 = (RuleCall)cCollabStyleAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//CollaborationStyle returns CollaborationStyle:
		//    {CollaborationStyle}
		//    'CollaborationStyle'
		//    '{'
		//        ('collabStyle' collabStyle=CollaborationStyleType)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{CollaborationStyle}
		//'CollaborationStyle'
		//'{'
		//    ('collabStyle' collabStyle=CollaborationStyleType)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{CollaborationStyle}
		public Action getCollaborationStyleAction_0() { return cCollaborationStyleAction_0; }
		
		//'CollaborationStyle'
		public Keyword getCollaborationStyleKeyword_1() { return cCollaborationStyleKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('collabStyle' collabStyle=CollaborationStyleType)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'collabStyle'
		public Keyword getCollabStyleKeyword_3_0() { return cCollabStyleKeyword_3_0; }
		
		//collabStyle=CollaborationStyleType
		public Assignment getCollabStyleAssignment_3_1() { return cCollabStyleAssignment_3_1; }
		
		//CollaborationStyleType
		public RuleCall getCollabStyleCollaborationStyleTypeEnumRuleCall_3_1_0() { return cCollabStyleCollaborationStyleTypeEnumRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class DatabaseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.Database");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDatabaseAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDatabaseKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConnectionStringAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConnectionStringEStringParserRuleCall_2_0 = (RuleCall)cConnectionStringAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDatabaseTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDatabaseTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDatabaseTypeDatabaseTypeEnumRuleCall_4_1_0 = (RuleCall)cDatabaseTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Database returns Database:
		//    {Database}
		//    'Database'
		//    connectionString=EString
		//    '{'
		//        ('DatabaseType' DatabaseType=DatabaseType)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Database}
		//'Database'
		//connectionString=EString
		//'{'
		//    ('DatabaseType' DatabaseType=DatabaseType)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Database}
		public Action getDatabaseAction_0() { return cDatabaseAction_0; }
		
		//'Database'
		public Keyword getDatabaseKeyword_1() { return cDatabaseKeyword_1; }
		
		//connectionString=EString
		public Assignment getConnectionStringAssignment_2() { return cConnectionStringAssignment_2; }
		
		//EString
		public RuleCall getConnectionStringEStringParserRuleCall_2_0() { return cConnectionStringEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('DatabaseType' DatabaseType=DatabaseType)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'DatabaseType'
		public Keyword getDatabaseTypeKeyword_4_0() { return cDatabaseTypeKeyword_4_0; }
		
		//DatabaseType=DatabaseType
		public Assignment getDatabaseTypeAssignment_4_1() { return cDatabaseTypeAssignment_4_1; }
		
		//DatabaseType
		public RuleCall getDatabaseTypeDatabaseTypeEnumRuleCall_4_1_0() { return cDatabaseTypeDatabaseTypeEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class HighLevelCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.HighLevelCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cHighLevelCommandAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHighLevelCommandKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLowlevelcommandKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cLowlevelcommandAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cLowlevelcommandLowLevelCommandCrossReference_4_2_0 = (CrossReference)cLowlevelcommandAssignment_4_2.eContents().get(0);
		private final RuleCall cLowlevelcommandLowLevelCommandEStringParserRuleCall_4_2_0_1 = (RuleCall)cLowlevelcommandLowLevelCommandCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cLowlevelcommandAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cLowlevelcommandLowLevelCommandCrossReference_4_3_1_0 = (CrossReference)cLowlevelcommandAssignment_4_3_1.eContents().get(0);
		private final RuleCall cLowlevelcommandLowLevelCommandEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cLowlevelcommandLowLevelCommandCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//HighLevelCommand returns HighLevelCommand:
		//    {HighLevelCommand}
		//    'HighLevelCommand'
		//    name=EString
		//    '{'
		//        ('lowlevelcommand' '(' lowlevelcommand+=[LowLevelCommand|EString] ( "," lowlevelcommand+=[LowLevelCommand|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{HighLevelCommand}
		//'HighLevelCommand'
		//name=EString
		//'{'
		//    ('lowlevelcommand' '(' lowlevelcommand+=[LowLevelCommand|EString] ( "," lowlevelcommand+=[LowLevelCommand|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{HighLevelCommand}
		public Action getHighLevelCommandAction_0() { return cHighLevelCommandAction_0; }
		
		//'HighLevelCommand'
		public Keyword getHighLevelCommandKeyword_1() { return cHighLevelCommandKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('lowlevelcommand' '(' lowlevelcommand+=[LowLevelCommand|EString] ( "," lowlevelcommand+=[LowLevelCommand|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'lowlevelcommand'
		public Keyword getLowlevelcommandKeyword_4_0() { return cLowlevelcommandKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//lowlevelcommand+=[LowLevelCommand|EString]
		public Assignment getLowlevelcommandAssignment_4_2() { return cLowlevelcommandAssignment_4_2; }
		
		//[LowLevelCommand|EString]
		public CrossReference getLowlevelcommandLowLevelCommandCrossReference_4_2_0() { return cLowlevelcommandLowLevelCommandCrossReference_4_2_0; }
		
		//EString
		public RuleCall getLowlevelcommandLowLevelCommandEStringParserRuleCall_4_2_0_1() { return cLowlevelcommandLowLevelCommandEStringParserRuleCall_4_2_0_1; }
		
		//( "," lowlevelcommand+=[LowLevelCommand|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//lowlevelcommand+=[LowLevelCommand|EString]
		public Assignment getLowlevelcommandAssignment_4_3_1() { return cLowlevelcommandAssignment_4_3_1; }
		
		//[LowLevelCommand|EString]
		public CrossReference getLowlevelcommandLowLevelCommandCrossReference_4_3_1_0() { return cLowlevelcommandLowLevelCommandCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getLowlevelcommandLowLevelCommandEStringParserRuleCall_4_3_1_0_1() { return cLowlevelcommandLowLevelCommandEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class LowLevelCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.LowLevelCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLowLevelCommandKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCommandKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCommandAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCommandLowCommandsEnumRuleCall_4_0 = (RuleCall)cCommandAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LowLevelCommand returns LowLevelCommand:
		//    'LowLevelCommand'
		//    name=EString
		//    '{'
		//        'command' command=LowCommands
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'LowLevelCommand'
		//name=EString
		//'{'
		//    'command' command=LowCommands
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'LowLevelCommand'
		public Keyword getLowLevelCommandKeyword_0() { return cLowLevelCommandKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'command'
		public Keyword getCommandKeyword_3() { return cCommandKeyword_3; }
		
		//command=LowCommands
		public Assignment getCommandAssignment_4() { return cCommandAssignment_4; }
		
		//LowCommands
		public RuleCall getCommandLowCommandsEnumRuleCall_4_0() { return cCommandLowCommandsEnumRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class MergeStrategyElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.MergeStrategy");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDSMCompareEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDSMCompareDSMCompareKeyword_0_0 = (Keyword)cDSMCompareEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGitDiffEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGitDiffGitDiffKeyword_1_0 = (Keyword)cGitDiffEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum MergeStrategy returns MergeStrategy:
		//                DSMCompare = 'DSMCompare' | GitDiff = 'GitDiff';
		public EnumRule getRule() { return rule; }
		
		//DSMCompare = 'DSMCompare' | GitDiff = 'GitDiff'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DSMCompare = 'DSMCompare'
		public EnumLiteralDeclaration getDSMCompareEnumLiteralDeclaration_0() { return cDSMCompareEnumLiteralDeclaration_0; }
		
		//'DSMCompare'
		public Keyword getDSMCompareDSMCompareKeyword_0_0() { return cDSMCompareDSMCompareKeyword_0_0; }
		
		//GitDiff = 'GitDiff'
		public EnumLiteralDeclaration getGitDiffEnumLiteralDeclaration_1() { return cGitDiffEnumLiteralDeclaration_1; }
		
		//'GitDiff'
		public Keyword getGitDiffGitDiffKeyword_1_0() { return cGitDiffGitDiffKeyword_1_0; }
	}
	public class LowCommandsElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.LowCommands");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAddEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAddAddKeyword_0_0 = (Keyword)cAddEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCheckoutEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCheckoutCheckoutKeyword_1_0 = (Keyword)cCheckoutEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCheckoutCreateEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCheckoutCreateCheckoutCreateKeyword_2_0 = (Keyword)cCheckoutCreateEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cCloneEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cCloneCloneKeyword_3_0 = (Keyword)cCloneEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCommitEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCommitCommitKeyword_4_0 = (Keyword)cCommitEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cCherryPickEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cCherryPickCherryPickKeyword_5_0 = (Keyword)cCherryPickEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cCreateBranchEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cCreateBranchCreateBranchKeyword_6_0 = (Keyword)cCreateBranchEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cFetchEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cFetchFetchKeyword_7_0 = (Keyword)cFetchEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cInitEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cInitInitKeyword_8_0 = (Keyword)cInitEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cPullEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cPullPullKeyword_9_0 = (Keyword)cPullEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cPushEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cPushPushKeyword_10_0 = (Keyword)cPushEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cRemoteAddEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cRemoteAddRemoteAddKeyword_11_0 = (Keyword)cRemoteAddEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cRmEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cRmRmKeyword_12_0 = (Keyword)cRmEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cLogEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cLogLogKeyword_13_0 = (Keyword)cLogEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cOpenEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cOpenOpenKeyword_14_0 = (Keyword)cOpenEnumLiteralDeclaration_14.eContents().get(0);
		
		//enum LowCommands returns LowCommands:
		//                Add = 'Add' | Checkout = 'Checkout' | CheckoutCreate = 'CheckoutCreate' | Clone = 'Clone' | Commit = 'Commit' | CherryPick = 'CherryPick' | CreateBranch = 'CreateBranch' | Fetch = 'Fetch' | Init = 'Init' | Pull = 'Pull' | Push = 'Push' | RemoteAdd = 'RemoteAdd' | Rm = 'Rm' | Log = 'Log' | Open = 'Open';
		public EnumRule getRule() { return rule; }
		
		//Add = 'Add' | Checkout = 'Checkout' | CheckoutCreate = 'CheckoutCreate' | Clone = 'Clone' | Commit = 'Commit' | CherryPick = 'CherryPick' | CreateBranch = 'CreateBranch' | Fetch = 'Fetch' | Init = 'Init' | Pull = 'Pull' | Push = 'Push' | RemoteAdd = 'RemoteAdd' | Rm = 'Rm' | Log = 'Log' | Open = 'Open'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Add = 'Add'
		public EnumLiteralDeclaration getAddEnumLiteralDeclaration_0() { return cAddEnumLiteralDeclaration_0; }
		
		//'Add'
		public Keyword getAddAddKeyword_0_0() { return cAddAddKeyword_0_0; }
		
		//Checkout = 'Checkout'
		public EnumLiteralDeclaration getCheckoutEnumLiteralDeclaration_1() { return cCheckoutEnumLiteralDeclaration_1; }
		
		//'Checkout'
		public Keyword getCheckoutCheckoutKeyword_1_0() { return cCheckoutCheckoutKeyword_1_0; }
		
		//CheckoutCreate = 'CheckoutCreate'
		public EnumLiteralDeclaration getCheckoutCreateEnumLiteralDeclaration_2() { return cCheckoutCreateEnumLiteralDeclaration_2; }
		
		//'CheckoutCreate'
		public Keyword getCheckoutCreateCheckoutCreateKeyword_2_0() { return cCheckoutCreateCheckoutCreateKeyword_2_0; }
		
		//Clone = 'Clone'
		public EnumLiteralDeclaration getCloneEnumLiteralDeclaration_3() { return cCloneEnumLiteralDeclaration_3; }
		
		//'Clone'
		public Keyword getCloneCloneKeyword_3_0() { return cCloneCloneKeyword_3_0; }
		
		//Commit = 'Commit'
		public EnumLiteralDeclaration getCommitEnumLiteralDeclaration_4() { return cCommitEnumLiteralDeclaration_4; }
		
		//'Commit'
		public Keyword getCommitCommitKeyword_4_0() { return cCommitCommitKeyword_4_0; }
		
		//CherryPick = 'CherryPick'
		public EnumLiteralDeclaration getCherryPickEnumLiteralDeclaration_5() { return cCherryPickEnumLiteralDeclaration_5; }
		
		//'CherryPick'
		public Keyword getCherryPickCherryPickKeyword_5_0() { return cCherryPickCherryPickKeyword_5_0; }
		
		//CreateBranch = 'CreateBranch'
		public EnumLiteralDeclaration getCreateBranchEnumLiteralDeclaration_6() { return cCreateBranchEnumLiteralDeclaration_6; }
		
		//'CreateBranch'
		public Keyword getCreateBranchCreateBranchKeyword_6_0() { return cCreateBranchCreateBranchKeyword_6_0; }
		
		//Fetch = 'Fetch'
		public EnumLiteralDeclaration getFetchEnumLiteralDeclaration_7() { return cFetchEnumLiteralDeclaration_7; }
		
		//'Fetch'
		public Keyword getFetchFetchKeyword_7_0() { return cFetchFetchKeyword_7_0; }
		
		//Init = 'Init'
		public EnumLiteralDeclaration getInitEnumLiteralDeclaration_8() { return cInitEnumLiteralDeclaration_8; }
		
		//'Init'
		public Keyword getInitInitKeyword_8_0() { return cInitInitKeyword_8_0; }
		
		//Pull = 'Pull'
		public EnumLiteralDeclaration getPullEnumLiteralDeclaration_9() { return cPullEnumLiteralDeclaration_9; }
		
		//'Pull'
		public Keyword getPullPullKeyword_9_0() { return cPullPullKeyword_9_0; }
		
		//Push = 'Push'
		public EnumLiteralDeclaration getPushEnumLiteralDeclaration_10() { return cPushEnumLiteralDeclaration_10; }
		
		//'Push'
		public Keyword getPushPushKeyword_10_0() { return cPushPushKeyword_10_0; }
		
		//RemoteAdd = 'RemoteAdd'
		public EnumLiteralDeclaration getRemoteAddEnumLiteralDeclaration_11() { return cRemoteAddEnumLiteralDeclaration_11; }
		
		//'RemoteAdd'
		public Keyword getRemoteAddRemoteAddKeyword_11_0() { return cRemoteAddRemoteAddKeyword_11_0; }
		
		//Rm = 'Rm'
		public EnumLiteralDeclaration getRmEnumLiteralDeclaration_12() { return cRmEnumLiteralDeclaration_12; }
		
		//'Rm'
		public Keyword getRmRmKeyword_12_0() { return cRmRmKeyword_12_0; }
		
		//Log = 'Log'
		public EnumLiteralDeclaration getLogEnumLiteralDeclaration_13() { return cLogEnumLiteralDeclaration_13; }
		
		//'Log'
		public Keyword getLogLogKeyword_13_0() { return cLogLogKeyword_13_0; }
		
		//Open = 'Open'
		public EnumLiteralDeclaration getOpenEnumLiteralDeclaration_14() { return cOpenEnumLiteralDeclaration_14; }
		
		//'Open'
		public Keyword getOpenOpenKeyword_14_0() { return cOpenOpenKeyword_14_0; }
	}
	public class LabelTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.LabelType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUniqueEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUniqueUniqueKeyword_0_0 = (Keyword)cUniqueEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCommitHashEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCommitHashCommitHashKeyword_1_0 = (Keyword)cCommitHashEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLabelEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLabelLabelKeyword_2_0 = (Keyword)cLabelEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum LabelType returns LabelType:
		//                Unique = 'Unique' | CommitHash = 'CommitHash' | Label = 'Label';
		public EnumRule getRule() { return rule; }
		
		//Unique = 'Unique' | CommitHash = 'CommitHash' | Label = 'Label'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Unique = 'Unique'
		public EnumLiteralDeclaration getUniqueEnumLiteralDeclaration_0() { return cUniqueEnumLiteralDeclaration_0; }
		
		//'Unique'
		public Keyword getUniqueUniqueKeyword_0_0() { return cUniqueUniqueKeyword_0_0; }
		
		//CommitHash = 'CommitHash'
		public EnumLiteralDeclaration getCommitHashEnumLiteralDeclaration_1() { return cCommitHashEnumLiteralDeclaration_1; }
		
		//'CommitHash'
		public Keyword getCommitHashCommitHashKeyword_1_0() { return cCommitHashCommitHashKeyword_1_0; }
		
		//Label = 'Label'
		public EnumLiteralDeclaration getLabelEnumLiteralDeclaration_2() { return cLabelEnumLiteralDeclaration_2; }
		
		//'Label'
		public Keyword getLabelLabelKeyword_2_0() { return cLabelLabelKeyword_2_0; }
	}
	public class VersionUnitTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.VersionUnitType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLineEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLineLineKeyword_0_0 = (Keyword)cLineEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSemanticEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSemanticSemanticKeyword_1_0 = (Keyword)cSemanticEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFileEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFileFileKeyword_2_0 = (Keyword)cFileEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cElementEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cElementElementKeyword_3_0 = (Keyword)cElementEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum VersionUnitType returns VersionUnitType:
		//                Line = 'Line' | Semantic = 'Semantic' | File = 'File' | Element = 'Element';
		public EnumRule getRule() { return rule; }
		
		//Line = 'Line' | Semantic = 'Semantic' | File = 'File' | Element = 'Element'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Line = 'Line'
		public EnumLiteralDeclaration getLineEnumLiteralDeclaration_0() { return cLineEnumLiteralDeclaration_0; }
		
		//'Line'
		public Keyword getLineLineKeyword_0_0() { return cLineLineKeyword_0_0; }
		
		//Semantic = 'Semantic'
		public EnumLiteralDeclaration getSemanticEnumLiteralDeclaration_1() { return cSemanticEnumLiteralDeclaration_1; }
		
		//'Semantic'
		public Keyword getSemanticSemanticKeyword_1_0() { return cSemanticSemanticKeyword_1_0; }
		
		//File = 'File'
		public EnumLiteralDeclaration getFileEnumLiteralDeclaration_2() { return cFileEnumLiteralDeclaration_2; }
		
		//'File'
		public Keyword getFileFileKeyword_2_0() { return cFileFileKeyword_2_0; }
		
		//Element = 'Element'
		public EnumLiteralDeclaration getElementEnumLiteralDeclaration_3() { return cElementEnumLiteralDeclaration_3; }
		
		//'Element'
		public Keyword getElementElementKeyword_3_0() { return cElementElementKeyword_3_0; }
	}
	public class CollaborationStyleTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.CollaborationStyleType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLocalOnlyEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLocalOnlyLocalOnlyKeyword_0_0 = (Keyword)cLocalOnlyEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRemoteEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRemoteRemoteKeyword_1_0 = (Keyword)cRemoteEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum CollaborationStyleType returns CollaborationStyleType:
		//                LocalOnly = 'LocalOnly' | Remote = 'Remote';
		public EnumRule getRule() { return rule; }
		
		//LocalOnly = 'LocalOnly' | Remote = 'Remote'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LocalOnly = 'LocalOnly'
		public EnumLiteralDeclaration getLocalOnlyEnumLiteralDeclaration_0() { return cLocalOnlyEnumLiteralDeclaration_0; }
		
		//'LocalOnly'
		public Keyword getLocalOnlyLocalOnlyKeyword_0_0() { return cLocalOnlyLocalOnlyKeyword_0_0; }
		
		//Remote = 'Remote'
		public EnumLiteralDeclaration getRemoteEnumLiteralDeclaration_1() { return cRemoteEnumLiteralDeclaration_1; }
		
		//'Remote'
		public Keyword getRemoteRemoteKeyword_1_0() { return cRemoteRemoteKeyword_1_0; }
	}
	public class DatabaseTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "diro.geodes.VcsFeatures.DatabaseType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMongoDBEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMongoDBMongoDBKeyword_0_0 = (Keyword)cMongoDBEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cXMIEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cXMIXMIKeyword_1_0 = (Keyword)cXMIEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNeo4JEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNeo4JNeo4JKeyword_2_0 = (Keyword)cNeo4JEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSQLEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSQLSQLKeyword_3_0 = (Keyword)cSQLEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum DatabaseType returns DatabaseType:
		//                MongoDB = 'MongoDB' | XMI = 'XMI' | Neo4J = 'Neo4J' | SQL = 'SQL';
		public EnumRule getRule() { return rule; }
		
		//MongoDB = 'MongoDB' | XMI = 'XMI' | Neo4J = 'Neo4J' | SQL = 'SQL'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MongoDB = 'MongoDB'
		public EnumLiteralDeclaration getMongoDBEnumLiteralDeclaration_0() { return cMongoDBEnumLiteralDeclaration_0; }
		
		//'MongoDB'
		public Keyword getMongoDBMongoDBKeyword_0_0() { return cMongoDBMongoDBKeyword_0_0; }
		
		//XMI = 'XMI'
		public EnumLiteralDeclaration getXMIEnumLiteralDeclaration_1() { return cXMIEnumLiteralDeclaration_1; }
		
		//'XMI'
		public Keyword getXMIXMIKeyword_1_0() { return cXMIXMIKeyword_1_0; }
		
		//Neo4J = 'Neo4J'
		public EnumLiteralDeclaration getNeo4JEnumLiteralDeclaration_2() { return cNeo4JEnumLiteralDeclaration_2; }
		
		//'Neo4J'
		public Keyword getNeo4JNeo4JKeyword_2_0() { return cNeo4JNeo4JKeyword_2_0; }
		
		//SQL = 'SQL'
		public EnumLiteralDeclaration getSQLEnumLiteralDeclaration_3() { return cSQLEnumLiteralDeclaration_3; }
		
		//'SQL'
		public Keyword getSQLSQLKeyword_3_0() { return cSQLSQLKeyword_3_0; }
	}
	
	private final VCSFeaturesElements pVCSFeatures;
	private final CommandsElements pCommands;
	private final HistoryElements pHistory;
	private final VersionUnitElements pVersionUnit;
	private final CollaborationStyleElements pCollaborationStyle;
	private final DatabaseElements pDatabase;
	private final EStringElements pEString;
	private final MergeStrategyElements eMergeStrategy;
	private final HighLevelCommandElements pHighLevelCommand;
	private final LowLevelCommandElements pLowLevelCommand;
	private final LowCommandsElements eLowCommands;
	private final LabelTypeElements eLabelType;
	private final EIntElements pEInt;
	private final VersionUnitTypeElements eVersionUnitType;
	private final CollaborationStyleTypeElements eCollaborationStyleType;
	private final DatabaseTypeElements eDatabaseType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public VcsFeaturesGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pVCSFeatures = new VCSFeaturesElements();
		this.pCommands = new CommandsElements();
		this.pHistory = new HistoryElements();
		this.pVersionUnit = new VersionUnitElements();
		this.pCollaborationStyle = new CollaborationStyleElements();
		this.pDatabase = new DatabaseElements();
		this.pEString = new EStringElements();
		this.eMergeStrategy = new MergeStrategyElements();
		this.pHighLevelCommand = new HighLevelCommandElements();
		this.pLowLevelCommand = new LowLevelCommandElements();
		this.eLowCommands = new LowCommandsElements();
		this.eLabelType = new LabelTypeElements();
		this.pEInt = new EIntElements();
		this.eVersionUnitType = new VersionUnitTypeElements();
		this.eCollaborationStyleType = new CollaborationStyleTypeElements();
		this.eDatabaseType = new DatabaseTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("diro.geodes.VcsFeatures".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//VCSFeatures returns VCSFeatures:
	//    {VCSFeatures}
	//    'VCSFeatures'
	//    name=EString
	//    '{'
	//        ('commands' '{' commands+=Commands ( "," commands+=Commands)* '}' )?
	//        ('history' '{' history+=History ( "," history+=History)* '}' )?
	//        ('versionunit' '{' versionunit+=VersionUnit ( "," versionunit+=VersionUnit)* '}' )?
	//        ('collaborationstyle' '{' collaborationstyle+=CollaborationStyle ( "," collaborationstyle+=CollaborationStyle)* '}' )?
	//        ('database' '{' database+=Database ( "," database+=Database)* '}' )?
	//    '}';
	public VCSFeaturesElements getVCSFeaturesAccess() {
		return pVCSFeatures;
	}
	
	public ParserRule getVCSFeaturesRule() {
		return getVCSFeaturesAccess().getRule();
	}
	
	//Commands returns Commands:
	//    {Commands}
	//    'Commands'
	//    '{'
	//        ('mergeStrategy' mergeStrategy=MergeStrategy)?
	//        ('highlevelcommand' '{' highlevelcommand+=HighLevelCommand ( "," highlevelcommand+=HighLevelCommand)* '}' )?
	//        ('lowlevelcommand' '{' lowlevelcommand+=LowLevelCommand ( "," lowlevelcommand+=LowLevelCommand)* '}' )?
	//    '}';
	public CommandsElements getCommandsAccess() {
		return pCommands;
	}
	
	public ParserRule getCommandsRule() {
		return getCommandsAccess().getRule();
	}
	
	//History returns History:
	//    {History}
	//    'History'
	//    '{'
	//        ('labelType' labelType=LabelType)?
	//        ('commitHistoryRange' commitHistoryRange=EInt)?
	//        ('numberOfBranches' numberOfBranches=EInt)?
	//    '}';
	public HistoryElements getHistoryAccess() {
		return pHistory;
	}
	
	public ParserRule getHistoryRule() {
		return getHistoryAccess().getRule();
	}
	
	//VersionUnit returns VersionUnit:
	//    {VersionUnit}
	//    'VersionUnit'
	//    '{'
	//        ('granularity' '{' granularity+=VersionUnitType ( "," granularity+=VersionUnitType)* '}' )?
	//    '}';
	public VersionUnitElements getVersionUnitAccess() {
		return pVersionUnit;
	}
	
	public ParserRule getVersionUnitRule() {
		return getVersionUnitAccess().getRule();
	}
	
	//CollaborationStyle returns CollaborationStyle:
	//    {CollaborationStyle}
	//    'CollaborationStyle'
	//    '{'
	//        ('collabStyle' collabStyle=CollaborationStyleType)?
	//    '}';
	public CollaborationStyleElements getCollaborationStyleAccess() {
		return pCollaborationStyle;
	}
	
	public ParserRule getCollaborationStyleRule() {
		return getCollaborationStyleAccess().getRule();
	}
	
	//Database returns Database:
	//    {Database}
	//    'Database'
	//    connectionString=EString
	//    '{'
	//        ('DatabaseType' DatabaseType=DatabaseType)?
	//    '}';
	public DatabaseElements getDatabaseAccess() {
		return pDatabase;
	}
	
	public ParserRule getDatabaseRule() {
		return getDatabaseAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum MergeStrategy returns MergeStrategy:
	//                DSMCompare = 'DSMCompare' | GitDiff = 'GitDiff';
	public MergeStrategyElements getMergeStrategyAccess() {
		return eMergeStrategy;
	}
	
	public EnumRule getMergeStrategyRule() {
		return getMergeStrategyAccess().getRule();
	}
	
	//HighLevelCommand returns HighLevelCommand:
	//    {HighLevelCommand}
	//    'HighLevelCommand'
	//    name=EString
	//    '{'
	//        ('lowlevelcommand' '(' lowlevelcommand+=[LowLevelCommand|EString] ( "," lowlevelcommand+=[LowLevelCommand|EString])* ')' )?
	//    '}';
	public HighLevelCommandElements getHighLevelCommandAccess() {
		return pHighLevelCommand;
	}
	
	public ParserRule getHighLevelCommandRule() {
		return getHighLevelCommandAccess().getRule();
	}
	
	//LowLevelCommand returns LowLevelCommand:
	//    'LowLevelCommand'
	//    name=EString
	//    '{'
	//        'command' command=LowCommands
	//    '}';
	public LowLevelCommandElements getLowLevelCommandAccess() {
		return pLowLevelCommand;
	}
	
	public ParserRule getLowLevelCommandRule() {
		return getLowLevelCommandAccess().getRule();
	}
	
	//enum LowCommands returns LowCommands:
	//                Add = 'Add' | Checkout = 'Checkout' | CheckoutCreate = 'CheckoutCreate' | Clone = 'Clone' | Commit = 'Commit' | CherryPick = 'CherryPick' | CreateBranch = 'CreateBranch' | Fetch = 'Fetch' | Init = 'Init' | Pull = 'Pull' | Push = 'Push' | RemoteAdd = 'RemoteAdd' | Rm = 'Rm' | Log = 'Log' | Open = 'Open';
	public LowCommandsElements getLowCommandsAccess() {
		return eLowCommands;
	}
	
	public EnumRule getLowCommandsRule() {
		return getLowCommandsAccess().getRule();
	}
	
	//enum LabelType returns LabelType:
	//                Unique = 'Unique' | CommitHash = 'CommitHash' | Label = 'Label';
	public LabelTypeElements getLabelTypeAccess() {
		return eLabelType;
	}
	
	public EnumRule getLabelTypeRule() {
		return getLabelTypeAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum VersionUnitType returns VersionUnitType:
	//                Line = 'Line' | Semantic = 'Semantic' | File = 'File' | Element = 'Element';
	public VersionUnitTypeElements getVersionUnitTypeAccess() {
		return eVersionUnitType;
	}
	
	public EnumRule getVersionUnitTypeRule() {
		return getVersionUnitTypeAccess().getRule();
	}
	
	//enum CollaborationStyleType returns CollaborationStyleType:
	//                LocalOnly = 'LocalOnly' | Remote = 'Remote';
	public CollaborationStyleTypeElements getCollaborationStyleTypeAccess() {
		return eCollaborationStyleType;
	}
	
	public EnumRule getCollaborationStyleTypeRule() {
		return getCollaborationStyleTypeAccess().getRule();
	}
	
	//enum DatabaseType returns DatabaseType:
	//                MongoDB = 'MongoDB' | XMI = 'XMI' | Neo4J = 'Neo4J' | SQL = 'SQL';
	public DatabaseTypeElements getDatabaseTypeAccess() {
		return eDatabaseType;
	}
	
	public EnumRule getDatabaseTypeRule() {
		return getDatabaseTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
